Traceback (most recent call last):
  File "C:\Users\orect\mambaforge\envs\pyFin\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\orect\mambaforge\envs\pyFin\Lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\orect\mambaforge\envs\pyFin\Lib\site-packages\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\orect\mambaforge\envs\pyFin\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\orect\mambaforge\envs\pyFin\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\orect\mambaforge\envs\pyFin\Lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\orect\mambaforge\envs\pyFin\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
for chapter in chapter_meta.keys():
    chapter_name = chapter_meta[chapter]["name"]
    chapter_subs = chapter_meta[chapter]["subs"]
    
    with open(f"{chapter}.md", "w") as f:
        f.write(header)
        f.write(f"# {chapter_name}\n\n")
        f.write(contents)
        f.write("\n\n")
        for sub in chapter_subs:
            f.write(f"#### {sub}\n")
            f.write(f"```{{code-cell}} julia\n")
            f.write(":tags: [\"hide-input\"]\n\n")

            with open(sub, "r") as g:
                f.write(g.read())
            f.write(f"```\n\n")
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mUnicodeDecodeError[0m                        Traceback (most recent call last)
Cell [1;32mIn[2], line 16[0m
[0;32m     13[0m f[38;5;241m.[39mwrite([38;5;124m"[39m[38;5;124m:tags: [[39m[38;5;130;01m\"[39;00m[38;5;124mhide-input[39m[38;5;130;01m\"[39;00m[38;5;124m][39m[38;5;130;01m\n[39;00m[38;5;130;01m\n[39;00m[38;5;124m"[39m)
[0;32m     15[0m [38;5;28;01mwith[39;00m [38;5;28mopen[39m(sub, [38;5;124m"[39m[38;5;124mr[39m[38;5;124m"[39m) [38;5;28;01mas[39;00m g:
[1;32m---> 16[0m     f[38;5;241m.[39mwrite([43mg[49m[38;5;241;43m.[39;49m[43mread[49m[43m([49m[43m)[49m)
[0;32m     17[0m f[38;5;241m.[39mwrite([38;5;124mf[39m[38;5;124m"[39m[38;5;124m```[39m[38;5;130;01m\n[39;00m[38;5;130;01m\n[39;00m[38;5;124m"[39m)

File [1;32m~\mambaforge\envs\pyFin\Lib\encodings\cp1252.py:23[0m, in [0;36mIncrementalDecoder.decode[1;34m(self, input, final)[0m
[0;32m     22[0m [38;5;28;01mdef[39;00m [38;5;21mdecode[39m([38;5;28mself[39m, [38;5;28minput[39m, final[38;5;241m=[39m[38;5;28;01mFalse[39;00m):
[1;32m---> 23[0m     [38;5;28;01mreturn[39;00m codecs[38;5;241m.[39mcharmap_decode([38;5;28minput[39m,[38;5;28mself[39m[38;5;241m.[39merrors,decoding_table)[[38;5;241m0[39m]

[1;31mUnicodeDecodeError[0m: 'charmap' codec can't decode byte 0x81 in position 47: character maps to <undefined>

